
name: "unknown c only learn value unkown value at sample nn seed 4 "

wandb_mode: "online"

numpy_seed: 4

load: False
load_path: 'params/k4g2v0ol.yaml'


device: 'cuda'

model:
  state_size: 6
  action_size: 3
  n_cons: 4
  n_value_func: 2
  penalty_factor: 1000

gym:
  pf: 1000
  noise_std: 1

plotting:
  window_size: 10

critic:
  lr: 0.01
  df: 0.9
  eps: 0.01

actor:
  sampled_grad: True
  nn_sample: True
  lr: 0.001
  beta: 0.05
  sample: False
  num_samples: 0.3


train_iters: 20
rollout_iters: 1000
total_iters: 100000


explicit_sol_time: 4
comp_expected: False
comp_expected_every: 100
