
name: "big_rig_run"

numpy_seed: 5

model:
  prob_size: 3
  n_cons: 6
  n_value_func: 2
  penalty_factor: 100



plotting:
  window_size: 100

critic:
  lr: 0.1
  df: 0.9
  eps: 0.01

actor:
  lr: 0.1
  beta: 0.5
  sample: False
  num_samples: 0.5


train_iters: 10
rollout_iters: 10
total_iters: 10000
