
name: "Should_be_corr_but_b_could_b_wrong"

wandb_mode: "online"

numpy_seed: 5

model:
  prob_size: 3
  n_cons: 6
  n_value_func: 2
  penalty_factor: 100

gym:
  pf: 1

plotting:
  window_size: 100

critic:
  lr: 0.01
  df: 0.9
  eps: 0.01

actor:
  nn_sample: False
  lr: 0.01
  beta: 0.5
  sample: False
  num_samples: 0.5


train_iters: 20
rollout_iters: 300
total_iters: 10000
