
name: "neg_grad"

wandb_mode: "online"

numpy_seed: 16

load: False
load_path: 'params/k4g2v0ol.yaml'


device: 'cuda'

model:
  state_size: 6
  action_size: 3
  n_cons: 6
  n_value_func: 2
  penalty_factor: 100

gym:
  pf: 100
  noise_std: 0.1

plotting:
  window_size: 100

critic:
  lr: 0.01
  df: 0.9
  eps: 0.01

actor:
  nn_sample: False
  lr: 0.01
  beta: 0.05
  sample: True
  num_samples: 0.3


train_iters: 20
rollout_iters: 500
total_iters: 100000


explicit_sol_time: 4
comp_expected: False
comp_expected_every: 50
